function saveAllFigsToPPT( filename )
hvis = get(0,'HandleVisibility');
set(0,'HandleVisibility','on');
nfigs = get(0,'Children');
set(0,'HandleVisibility',hvis)

isOpen  = exportToPPTX();
if ~isempty(isOpen),
    % If PowerPoint already started, then close first and then open a new one
    exportToPPTX('close');
end

exportToPPTX('new','Dimensions',[12 6], ...
    'Title','Calcium Analysis', ...
    'Author','MatLab', ...
    'Subject','Automatically generated PPTX file', ...
    'Comments','This file has been automatically generated by exportToPPTX');


for i = 1:length(nfigs)
    figH = figure(i);
    slideNum = exportToPPTX('addslide');
    exportToPPTX('addpicture',figH);
    close(figH)
end
newFile = exportToPPTX('saveandclose',filename);


end

